#cloud-config
groups:
  - docker
users:
  - default
hostname: ${hostname}
package_update: true
package_upgrade: true
packages:
  - git
  - telnet
runcmd:
  - apt-get update
  - apt-get install -y ca-certificates curl gnupg lsb-release
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get upgrade
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - usermod -aG docker admin
  - ssh-keygen -q -b 2048 -f /root/.ssh/id_rsa -N ""